language: python
sudo: false
matrix:
    include:
    - python: "3.3"
      env: DEPS="numpy scipy nose cython"
    - python: "3.5"
      env: DEPS="numpy scipy nose cython"
    - python: "2.7"
      env: DEPS="numpy=1.10.4 scipy=0.17 nose cython"

# setup adapted from https://github.com/soft-matter/trackpy/blob/master/.travis.yml
before_install:
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
    # See:
    # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
    - conda update --yes --no-deps conda
    # Learned the hard way: miniconda is not always up-to-date with conda.
    - conda update --yes conda

install: 
    - conda install --yes -c conda conda-env
    - conda install --yes $DEPS pip
    - conda info -a
    - pip install coveralls 
    - which python
    - python setup.py build_ext --inplace
    - python setup.py install
    - cd ..


# command to run tests
script: 
    - nosetests ./py-speedyfx/speedyfx/tests/ --with-coverage --cover-package=speedyfx
#    - coverage run --source=hedp ./hedp/tests/run.py

#after_success:
#    coveralls

