language: python
sudo: false
matrix:
    include:
    - python: "3.5"
      env: SKLEARN="1" DEPS="numpy scipy cython"
    - python: "3.5"
      env: SKLEARN="0" DEPS="numpy scipy cython"
    - python: "3.3"
      env: SKLEARN="1" DEPS="numpy scipy cython"
    - python: "2.7"
      env: SKLEARN="1" DEPS="numpy=1.10.4 scipy=0.17 cython"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
    - conda update --yes conda
    - conda info -a

install: 
    - conda install --yes -c conda conda-env
    - conda install --yes $DEPS pip pytest
    - conda info -a
    - which python
    - if [ ${SKLEARN} == "1" ]; then pip install scikit-learn==0.18rc2; fi
    - python setup.py build_ext --inplace
    - python setup.py install
    - cd ..


script: 
    - py.test -sv ./py-speedyfx/speedyfx/

#after_success:
#    coveralls

